# [Spring 환경 설정 시 properties 파일의 한계로 yaml 파일 선호]
# yaml 파일은 계층구조로 표현하여 가독성이 좋으며, 불필요한 소스의 중복도 제거 할 수 있다.
# 들여쓰기, 띄어쓰기로 구분하여 보기 편하다
# 또한 개발 환경별 설정 파일 분리 지원한다
---
#가장 기본적인 설정만을 셋팅하는 파일
#세부적인 사항은 application-dev나 prod 파일에서 오버라이딩 하여 사용함
# 공통 환경 설정
# WebServer 설정
server:
  port: 80

---

# Spring profiles 설정
spring: 
  profiles:
    default: dev                 # 개발 환경을 dev로 설정