/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-28 00:41:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.modules;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1689922308000L));
    _jspx_dependants.put("jar:file:/C:/ezen-fullstack/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project_shoppingmall/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("        <div class=\"footer_wrap\">\r\n");
      out.write("          <!-- 텍스트 상단에 위치한 icon 이미지 -->\r\n");
      out.write("          <ul class=\"footer_mark\">\r\n");
      out.write("            <!-- 페이스북 -->\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <i class=\"icon-facebook\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- 인스타그램 -->\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <i class=\"icon-instagram\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- 유튜브 -->\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <i class=\"icon-youtube-play\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <img src=\"/img/kakaotalk.png\" alt=\"\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- 첫째줄 text 컨텐츠 -->\r\n");
      out.write("        <div class=\"footer_link_left\">\r\n");
      out.write("          <a href=\"#\" class=\"footer_item\">사이트맵</a>\r\n");
      out.write("          <a href=\"#\" class=\"footer_item\">로그인</a>\r\n");
      out.write("          <a href=\"#\" class=\"footer_item\">회원가입</a><br>\r\n");
      out.write("          <a href=\"#\" class=\"footer_item_company\">회사소개</a>\r\n");
      out.write("          <a href=\"#\" class=\"footer_item_sys\">서비스이용약관</a>\r\n");
      out.write("          <a href=\"#\" class=\"footer_item_sys\">개인정보처리방침</a>\r\n");
      out.write("          <a href=\"#\" class=\"footer_item_sys\">영상정보처리방침</a>\r\n");
      out.write("          <a href=\"#\" class=\"footer_item_sys\">뷰티포인트</a><br>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer_link_left2\">\r\n");
      out.write("          <a href=\"#\" class=\"footer_item\">고객상담팀(수신자요금부담): 080-123-4567</a>\r\n");
      out.write("          <span class=\"footer_item time\">[상담시간] 월~금:AM 09:00~PM 06:00</span><br>\r\n");
      out.write("          <span class=\"footer_item copyright\">\r\n");
      out.write("            © AMOREPACIFIC CORPORATION. All rights reserved.\r\n");
      out.write("          </span>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- footer 이미지 하단에 위치한 text 컨텐츠들 -->\r\n");
      out.write("        <div class=\"footer_legal\">\r\n");
      out.write("         \r\n");
      out.write("          \r\n");
      out.write("          <div class=\"wa\">\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("              <img src=\"/img/wa.png\" alt=\"01\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 웹표준 w3c 아이콘 -->\r\n");
      out.write("          <p class=\"w3c\">\r\n");
      out.write("            <a href=\"http://validator.kldp.org/check?uri=referer\"\r\n");
      out.write("              onclick=\"this.href=this.href.replace(/referer$/,encodeURIComponent(document.URL))\"><img\r\n");
      out.write("                src=\"//validator.kldp.org/w3cimgs/validate/html5-orange.png\" alt=\"Valid HTML 5\" height=\"15\"\r\n");
      out.write("                width=\"80\"></a>\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
