/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-28 05:06:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1689922308000L));
    _jspx_dependants.put("jar:file:/C:/ezen-fullstack/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project_shoppingmall/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>헤라 | 빈틈없이 밀착되는 맑은 컬러감</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1.0, user-scalable=no, minimal-ui\">\r\n");
      out.write("<!-- style, script 모듈화 -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/modules/style-script.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 전체영역 -->\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		<!-- 우측하단 버튼 모듈화 -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/modules/option.jsp", out, false);
      out.write("\r\n");
      out.write("		<!-- 사이드 메뉴 모듈화 -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/modules/sidemenu.jsp", out, false);
      out.write("\r\n");
      out.write("		<!-- header 영역 모듈화 -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/modules/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- SECTION1 메인화면 영역 -->\r\n");
      out.write("		<div class=\"visual\">\r\n");
      out.write("			<!-- 이미지 좌우측에 있는 뒤로가기 , 앞으로가기 버튼 -->\r\n");
      out.write("			<button class=\"visu_arrow left\">left</button>\r\n");
      out.write("			<button class=\"visu_arrow right\">right</button>\r\n");
      out.write("			<!-- 슬라이드 되는 이미지를 감싸는 전체영역 -->\r\n");
      out.write("			<ul class=\"visual_wrap\">\r\n");
      out.write("				<!-- 슬라이드 되는 메인이미지 컨텐츠1 -->\r\n");
      out.write("				<li class=\"visu_slide\">\r\n");
      out.write("					<div class=\"visu_veil\"></div>\r\n");
      out.write("					<div class=\"visu_txt_wrap\">\r\n");
      out.write("						<div class=\"visu_txt_cont\">\r\n");
      out.write("							<div class=\"visu_txt_cont_cell\">\r\n");
      out.write("								<h1>처음 바른 그대로 매끈한 실키 스킨</h1>\r\n");
      out.write("								<p>실키 스테이 파운데이션</p>\r\n");
      out.write("								<div class=\"visu_btn_wrap\">\r\n");
      out.write("									<a href=\"#\" class=\"btn_view\">자세히 보기</a> <a href=\"#\"\r\n");
      out.write("										class=\"btn_view\">구매하러 가기</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 슬라이드 되는 메인이미지 컨텐츠2 -->\r\n");
      out.write("				<li class=\"visu_slide\">\r\n");
      out.write("					<div class=\"visu_veil\"></div>\r\n");
      out.write("					<div class=\"visu_txt_wrap\">\r\n");
      out.write("						<div class=\"visu_txt_cont\">\r\n");
      out.write("							<div class=\"visu_txt_cont_cell\">\r\n");
      out.write("								<h1>광채를 되찾아주는 피치빛 생기 톤업</h1>\r\n");
      out.write("								<p>UV 프로텍터 톤업 SPF50+ / PA+++</p>\r\n");
      out.write("								<div class=\"visu_btn_wrap\">\r\n");
      out.write("									<a href=\"#\" class=\"btn_view\">자세히 보기</a> <a href=\"#\"\r\n");
      out.write("										class=\"btn_view\">구매하러 가기</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 슬라이드 되는 메인이미지 컨텐츠3 -->\r\n");
      out.write("				<li class=\"visu_slide\">\r\n");
      out.write("					<div class=\"visu_veil\"></div>\r\n");
      out.write("					<div class=\"visu_txt_wrap\">\r\n");
      out.write("						<div class=\"visu_txt_cont\">\r\n");
      out.write("							<div class=\"visu_txt_cont_cell\">\r\n");
      out.write("								<h1>나다운 피부 표현의 완성</h1>\r\n");
      out.write("								<p>블랙 쿠션 & 스킨 래디언트 글로우 쿠션</p>\r\n");
      out.write("								<div class=\"visu_btn_wrap\">\r\n");
      out.write("									<a href=\"#\" class=\"btn_view\">자세히 보기</a> <a href=\"#\"\r\n");
      out.write("										class=\"btn_view\">구매하러 가기</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<!-- 컨텐츠 하단 - 이미지 순서를 나타내는 네비게이션 버튼 -->\r\n");
      out.write("			<ul class=\"visu_btm_wrap\">\r\n");
      out.write("				<!-- 해당 이미지로 이동하면 li에 class =\"act\" 가 자동으로 붙으면서 검은색버튼이 길어짐 -->\r\n");
      out.write("				<li><a href=\"#\">btn01</a></li>\r\n");
      out.write("				<li><a href=\"#\">btn02</a></li>\r\n");
      out.write("				<li><a href=\"#\">btn03</a></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 슬라이드 재생/정지 기능을 제어하기 위한 버튼 -->\r\n");
      out.write("				<li class=\"controls_wrap\">\r\n");
      out.write("					<button class=\"control start\">start</button>\r\n");
      out.write("					<button class=\"control stop\">stop</button>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 섹션2 : Today's Hot Menu 제품소개 영역 -->\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("		<!-- 컨텐츠의 위치를 제어하기위한 전체영역 -->\r\n");
      out.write("		<div class=\"recommend\">\r\n");
      out.write("			<!-- Today’s Hot Menu 텍스트 -->\r\n");
      out.write("			<h2 class=\"cont_title ct1\">SILKY STAY FOUNDATION</h2>\r\n");
      out.write("			<!-- choice - 선택한 메뉴의 카테고리에 맞는 제품의 이미지가 출력됨 -->\r\n");
      out.write("			<!-- 제품 이미지들의 위치를 제어하기위한 영역 -->\r\n");
      out.write("			<div class=\"recom_list_wrap\">\r\n");
      out.write("				<!-- 유튜브 비디오 -->\r\n");
      out.write("				<div class=\"video_wrap\">\r\n");
      out.write("					<iframe class=\"video img-h\" width=\"560\" height=\"315\"\r\n");
      out.write("						src=\"https://www.youtube.com/embed/eTdfSRK55Hk\"\r\n");
      out.write("						title=\"YouTube video player\" frameborder=\"0\"\r\n");
      out.write("						allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\r\n");
      out.write("						allowfullscreen></iframe>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 섹션3 : Product : 상품목록 -->\r\n");
      out.write("	<div class=\"product\">\r\n");
      out.write("		<h2 class=\"product_main_title\">NEW ITEM</h2>\r\n");
      out.write("		");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 섹션3 -->\r\n");
      out.write("	<div class=\"with\">\r\n");
      out.write("		<!-- 화면 상단 가운대에 위치한 메인 텍스트 -->\r\n");
      out.write("		<h2 class=\"cont_title ct2\">BEST ITEM</h2>\r\n");
      out.write("		<!-- 메인텍스트 바로 밑에 위치한 서브 텍스트 -->\r\n");
      out.write("		<span class=\"with_txt\"> <i class=\"icon-instagram\"></i> Check\r\n");
      out.write("			Instagram\r\n");
      out.write("		</span>\r\n");
      out.write("\r\n");
      out.write("		<!-- 이미지 전체 영역 -->\r\n");
      out.write("		<div class=\"with_list_wrap\">\r\n");
      out.write("			<!-- 이미지 전체 영역2 : Ul -->\r\n");
      out.write("			<ul class=\"with_list\">\r\n");
      out.write("\r\n");
      out.write("				<!-- 이미지 컨텐츠 1 -->\r\n");
      out.write("				<li class=\"w_list01\"><a href=\"/\" class=\"img_holder\">0</a> <!-- 이미지를 hover 했을때 밑에서부터 올라오는 Text 영역 -->\r\n");
      out.write("					<div class=\"info_holder\">\r\n");
      out.write("						<!-- 올라온 text 영역 배경 -->\r\n");
      out.write("						<svg viewBox=\"0 -5 240 51\" preserveAspectRatio=\"none\">\r\n");
      out.write("                    <path\r\n");
      out.write("								d=\"M120,0c82.1,0,100.6,39.2,120,39.2c0,0.7,0,3.6,0,6.7c-23.6,0-194.8,0-240,0c0-2.7,0-4.1,0-6.7C14,39.2,37.9,0,120,0z\"></path>\r\n");
      out.write("                  </svg>\r\n");
      out.write("						<!-- @ hover : 메인텍스트 -->\r\n");
      out.write("						<div class=\"info_content\">\r\n");
      out.write("							<div class=\"user_handle\">\r\n");
      out.write("								<a href=\"#\">@Hera</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- hover : 서브텍스트 -->\r\n");
      out.write("							<div class=\"user_caption\">센슈얼 글로우 피팅 틴트</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 이미지 컨텐츠 2 -->\r\n");
      out.write("				<li class=\"w_list02\"><a href=\"#\" class=\"img_holder\">0</a>\r\n");
      out.write("					<div class=\"info_holder\">\r\n");
      out.write("						<svg viewBox=\"0 -5 240 51\" preserveAspectRatio=\"none\">\r\n");
      out.write("                    <path\r\n");
      out.write("								d=\"M120,0c82.1,0,100.6,39.2,120,39.2c0,0.7,0,3.6,0,6.7c-23.6,0-194.8,0-240,0c0-2.7,0-4.1,0-6.7C14,39.2,37.9,0,120,0z\"></path>\r\n");
      out.write("                  </svg>\r\n");
      out.write("						<div class=\"info_content\">\r\n");
      out.write("							<div class=\"user_handle\">\r\n");
      out.write("								<a href=\"#\">@Hera</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"user_caption\">센슈얼 파우더 매트 리퀴드</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 이미지 컨텐츠 3 -->\r\n");
      out.write("				<li class=\"w_list03\"><a href=\"#\" class=\"img_holder\">0</a>\r\n");
      out.write("					<div class=\"info_holder\">\r\n");
      out.write("						<svg viewBox=\"0 -5 240 51\" preserveAspectRatio=\"none\">\r\n");
      out.write("                    <path\r\n");
      out.write("								d=\"M120,0c82.1,0,100.6,39.2,120,39.2c0,0.7,0,3.6,0,6.7c-23.6,0-194.8,0-240,0c0-2.7,0-4.1,0-6.7C14,39.2,37.9,0,120,0z\"></path>\r\n");
      out.write("                  </svg>\r\n");
      out.write("						<div class=\"info_content\">\r\n");
      out.write("							<div class=\"user_handle\">\r\n");
      out.write("								<a href=\"#\">@Hera</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"user_caption\">실키 스테이 24H 롱웨어 파운데이션</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 이미지 컨텐츠 4 -->\r\n");
      out.write("				<li class=\"w_list04\"><a href=\"#\" class=\"img_holder\">0</a>\r\n");
      out.write("					<div class=\"info_holder\">\r\n");
      out.write("						<svg viewBox=\"0 -5 240 51\" preserveAspectRatio=\"none\">\r\n");
      out.write("                    <path\r\n");
      out.write("								d=\"M120,0c82.1,0,100.6,39.2,120,39.2c0,0.7,0,3.6,0,6.7c-23.6,0-194.8,0-240,0c0-2.7,0-4.1,0-6.7C14,39.2,37.9,0,120,0z\"></path>\r\n");
      out.write("                  </svg>\r\n");
      out.write("						<div class=\"info_content\">\r\n");
      out.write("							<div class=\"user_handle\">\r\n");
      out.write("								<a href=\"#\">@Hera</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"user_caption\">UV 프로텍터 액티브 선 밤</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 섹션4 : 중앙 배너 -->\r\n");
      out.write("	<div class=\"mid_banner\">\r\n");
      out.write("		<div class=\"text_contents\">\r\n");
      out.write("			<h2 class=\"mid_banner_maintext\">베스트 셀러</h2>\r\n");
      out.write("			<p class=\"mid_banner_subtext\">\r\n");
      out.write("				건강하게 빛나고 힘있게 채우는<br> 헤라의 시그니처 케어\r\n");
      out.write("			</p>\r\n");
      out.write("			<button class=\"mid_banner_bt\">\r\n");
      out.write("				<a href=\"#\">더보기</a>\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 섹션 5 : 제품 소개 페이지 -->\r\n");
      out.write("	<div class=\"perfume\" id=\"index_content\">\r\n");
      out.write("		<!-- 제품소개 . 텍스트영역 -->\r\n");
      out.write("		<div class=\"perfume_wrap pw01\">\r\n");
      out.write("\r\n");
      out.write("			<!-- 제품사진 -->\r\n");
      out.write("			<div class=\"perfume_img\">\r\n");
      out.write("				<a href=\"#\"> <img src=\"/img/hera/화장품/틴트/틴트2_상세3.jpg\" alt=\"01\">\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- 제품 설명 : 텍스트영역 -->\r\n");
      out.write("			<div class=\"perfume_txt\">\r\n");
      out.write("				<h3 class=\"perfume_main_txt\"># HERA LOVERS PICK!</h3>\r\n");
      out.write("				<p class=\"perfume_sub_txt\">\r\n");
      out.write("					어느 각도에서나 빈틈없이 <br> 반짝이는 GLAZED 글로우\r\n");
      out.write("				</p>\r\n");
      out.write("				<div class=\"desc\">NEW SENSUAL FITTING GLOW TINT</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"btn_wrap\">\r\n");
      out.write("					<a href=\"#\" class=\"btn_view\">자세히 보러가기</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 제품상세페이지로 이동하기 위한 버튼 -->\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 제품2 . 소개페이지 전체영역 -->\r\n");
      out.write("		<div class=\"perfume_wrap pw02\">\r\n");
      out.write("\r\n");
      out.write("			<!-- 제품사진 -->\r\n");
      out.write("			<div class=\"perfume_img\">\r\n");
      out.write("				<a href=\"#\"> <img src=\"/img/hera/lv5.jpg\" alt=\"01\">\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- 제품 설명 : 텍스트영역 -->\r\n");
      out.write("			<div class=\"perfume_txt\">\r\n");
      out.write("				<h3 class=\"perfume_main_txt\">WHAT'S NEW?</h3>\r\n");
      out.write("				<p class=\"perfume_sub_txt\">\r\n");
      out.write("					일상에서의 강력하고<br> 세심한 선케어를 위한<br> 클린 포뮬라의 수분 선 밤\r\n");
      out.write("				</p>\r\n");
      out.write("				<div class=\"desc\">UV 프로텍터 액티브 선 밤</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"btn_wrap\">\r\n");
      out.write("					<a href=\"#\" class=\"btn_view\">자세히 보러가기</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 섹션7 : 커뮤니티 , 인스타그램 -->\r\n");
      out.write("	<div class=\"culture\">\r\n");
      out.write("		<!-- 컨텐츠 전체영역 -->\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("			<a href=\"#\" class=\"content_img\"> <img src=\"/img/hera_logo2.png\" alt=\"\">\r\n");
      out.write("			</a>\r\n");
      out.write("			<!-- 서브 텍스트1 -->\r\n");
      out.write("			<p class=\"culture_txt\">\r\n");
      out.write("				Share your #HERA moments!\r\n");
      out.write("				<!-- 서브 텍스트2 -->\r\n");
      out.write("				<span> <i class=\"icon-instagram\"></i> 인스타그램에서 Hera 를 방문해보세요\r\n");
      out.write("				</span>\r\n");
      out.write("			</p>\r\n");
      out.write("			<!-- 이미지 컨텐츠 구획 -->\r\n");
      out.write("			<ul class=\"culture_list cfix\">\r\n");
      out.write("				<!-- 이미지1 -->\r\n");
      out.write("				<li>\r\n");
      out.write("					<!-- a태그에 css를 통해 이미지를 적용하였음 --> <a href=\"#\" class=\"img_holder\">0</a>\r\n");
      out.write("					<!-- 이미지를 호버했을시 나오는 컨텐츠 -->\r\n");
      out.write("					<div class=\"info_holder\">\r\n");
      out.write("						<!-- 호버했을때 나오는 컨텐츠의 배경 -->\r\n");
      out.write("						<svg viewBox=\"0 -5 240 51\" preserveAspectRatio=\"none\">\r\n");
      out.write("                  <path\r\n");
      out.write("								d=\"M120,0c82.1,0,100.6,39.2,120,39.2c0,0.7,0,3.6,0,6.7c-23.6,0-194.8,0-240,0c0-2.7,0-4.1,0-6.7C14,39.2,37.9,0,120,0z\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("						<!-- hover : 컨텐츠 텍스트1-->\r\n");
      out.write("						<div class=\"info_content\">\r\n");
      out.write("							<div class=\"user_handle\">\r\n");
      out.write("								<a href=\"#\">@Hera-Instagram</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- hover : 컨텐츠 텍스트2 -->\r\n");
      out.write("							<div class=\"user_caption\">엑스커베이션 블랙 쿠션</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 이미지2 -->\r\n");
      out.write("				<li><a href=\"#\" class=\"img_holder\">0</a>\r\n");
      out.write("					<div class=\"info_holder\">\r\n");
      out.write("						<svg viewBox=\"0 -5 240 51\" preserveAspectRatio=\"none\">\r\n");
      out.write("                  <path\r\n");
      out.write("								d=\"M120,0c82.1,0,100.6,39.2,120,39.2c0,0.7,0,3.6,0,6.7c-23.6,0-194.8,0-240,0c0-2.7,0-4.1,0-6.7C14,39.2,37.9,0,120,0z\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("						<div class=\"info_content\">\r\n");
      out.write("							<div class=\"user_handle\">\r\n");
      out.write("								<a href=\"#\">@Hera-Instagram</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"user_caption\">센슈얼 피팅 글로우 틴트</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 이미지3 -->\r\n");
      out.write("				<li><a href=\"#\" class=\"img_holder\">0</a>\r\n");
      out.write("					<div class=\"info_holder\">\r\n");
      out.write("						<svg viewBox=\"0 -5 240 51\" preserveAspectRatio=\"none\">\r\n");
      out.write("                  <path\r\n");
      out.write("								d=\"M120,0c82.1,0,100.6,39.2,120,39.2c0,0.7,0,3.6,0,6.7c-23.6,0-194.8,0-240,0c0-2.7,0-4.1,0-6.7C14,39.2,37.9,0,120,0z\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("						<div class=\"info_content\">\r\n");
      out.write("							<div class=\"user_handle\">\r\n");
      out.write("								<a href=\"#\">@Hera-Instagram</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"user_caption\">센슈얼 피팅 글로우 틴트</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 이미지4 -->\r\n");
      out.write("				<li><a href=\"#\" class=\"img_holder\">0</a>\r\n");
      out.write("					<div class=\"info_holder\">\r\n");
      out.write("						<svg viewBox=\"0 -5 240 51\" preserveAspectRatio=\"none\">\r\n");
      out.write("                  <path\r\n");
      out.write("								d=\"M120,0c82.1,0,100.6,39.2,120,39.2c0,0.7,0,3.6,0,6.7c-23.6,0-194.8,0-240,0c0-2.7,0-4.1,0-6.7C14,39.2,37.9,0,120,0z\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("						<div class=\"info_content\">\r\n");
      out.write("							<div class=\"user_handle\">\r\n");
      out.write("								<a href=\"#\">@Hera-Instagram</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"user_caption\">센슈얼 파우더 매트 리퀴드</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 이미지5 -->\r\n");
      out.write("				<li><a href=\"#\" class=\"img_holder\">0</a>\r\n");
      out.write("					<div class=\"info_holder\">\r\n");
      out.write("						<svg viewBox=\"0 -5 240 51\" preserveAspectRatio=\"none\">\r\n");
      out.write("                  <path\r\n");
      out.write("								d=\"M120,0c82.1,0,100.6,39.2,120,39.2c0,0.7,0,3.6,0,6.7c-23.6,0-194.8,0-240,0c0-2.7,0-4.1,0-6.7C14,39.2,37.9,0,120,0z\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("						<div class=\"info_content\">\r\n");
      out.write("							<div class=\"user_handle\">\r\n");
      out.write("								<a href=\"#\">@Hera-Instagram</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"user_caption\">UV 프로텍트 액티브 선 밤</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 이미지6 -->\r\n");
      out.write("				<li><a href=\"#\" class=\"img_holder\">0</a>\r\n");
      out.write("					<div class=\"info_holder\">\r\n");
      out.write("						<svg viewBox=\"0 -5 240 51\" preserveAspectRatio=\"none\">\r\n");
      out.write("                  <path\r\n");
      out.write("								d=\"M120,0c82.1,0,100.6,39.2,120,39.2c0,0.7,0,3.6,0,6.7c-23.6,0-194.8,0-240,0c0-2.7,0-4.1,0-6.7C14,39.2,37.9,0,120,0z\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("						<div class=\"info_content\">\r\n");
      out.write("							<div class=\"user_handle\">\r\n");
      out.write("								<a href=\"#\">@Hera-Instagram</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"user_caption\">센슈얼 파우더 매트 리퀴드</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 이미지7 -->\r\n");
      out.write("				<li><a href=\"#\" class=\"img_holder\">0</a>\r\n");
      out.write("					<div class=\"info_holder\">\r\n");
      out.write("						<svg viewBox=\"0 -5 240 51\" preserveAspectRatio=\"none\">\r\n");
      out.write("                  <path\r\n");
      out.write("								d=\"M120,0c82.1,0,100.6,39.2,120,39.2c0,0.7,0,3.6,0,6.7c-23.6,0-194.8,0-240,0c0-2.7,0-4.1,0-6.7C14,39.2,37.9,0,120,0z\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("						<div class=\"info_content\">\r\n");
      out.write("							<div class=\"user_handle\">\r\n");
      out.write("								<a href=\"#\">@Hera-Instagram</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"user_caption\">엑스커베이션 에디팅 박스</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- 이미지8 -->\r\n");
      out.write("				<li><a href=\"#\" class=\"img_holder\">0</a>\r\n");
      out.write("					<div class=\"info_holder\">\r\n");
      out.write("						<svg viewBox=\"0 -5 240 51\" preserveAspectRatio=\"none\">\r\n");
      out.write("                  <path\r\n");
      out.write("								d=\"M120,0c82.1,0,100.6,39.2,120,39.2c0,0.7,0,3.6,0,6.7c-23.6,0-194.8,0-240,0c0-2.7,0-4.1,0-6.7C14,39.2,37.9,0,120,0z\"></path>\r\n");
      out.write("                </svg>\r\n");
      out.write("						<div class=\"info_content\">\r\n");
      out.write("							<div class=\"user_handle\">\r\n");
      out.write("								<a href=\"#\">@Hera-Instagram</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"user_caption\">루즈 홀릭</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- footer 영역-->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/modules/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /index.jsp(125,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(125,2) '${product}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${product}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /index.jsp(125,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("product");
      // /index.jsp(125,2) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("			<!-- 1줄 innerHTML -->\r\n");
            out.write("			<div class=\"product_list\">\r\n");
            out.write("				<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/detail?proName=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.proName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write(' ');
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("				</a>\r\n");
            out.write("				<h1 class=\"product_name\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.proName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h1>\r\n");
            out.write("			</div>\r\n");
            out.write("\r\n");
            out.write("			");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write('\r');
            out.write('\n');
            out.write('	');
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /index.jsp(126,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index % 3 == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<!-- 새로운 행 시작 -->\r\n");
          out.write("				<div class=\"product_wrap\">\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /index.jsp(133,57) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(133,57) '${product.imgUrlList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${product.imgUrlList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /index.jsp(133,57) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("imageUrl");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						<img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imageUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"ProductImage\">\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /index.jsp(141,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index % 3 == 2 || status.last}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<!-- 행 닫기 -->\r\n");
          out.write("	</div>\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
