/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-28 00:55:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.shopping;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shopping_002dbag_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\" dir=\"ltr\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>헤라 : 장바구니</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1.0, user-scalable=no, minimal-ui\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/modules/style-script.jsp", out, false);
      out.write("\r\n");
      out.write("<script defer src=\"js/shopping.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 전체영역 -->\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("		<!-- 우측하단 버튼 모듈화 -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/modules/option.jsp", out, false);
      out.write("\r\n");
      out.write("		<!-- 사이드 메뉴 모듈화 -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/modules/sidemenu.jsp", out, false);
      out.write("\r\n");
      out.write("		<!-- header 영역 모듈화 -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/modules/header.jsp", out, false);
      out.write("\r\n");
      out.write("		<!-- 쇼핑 페이지 시작 -->\r\n");
      out.write("	   <!-- 쇼핑 페이지 시작 -->\r\n");
      out.write("    <div class=\"shopping_page\">\r\n");
      out.write("      <!-- 장바구니 텍스트 -->\r\n");
      out.write("      <div class=\"shop_text\">\r\n");
      out.write("        <h2>장바구니</h2>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 전체선택 -->\r\n");
      out.write("      <div class=\"shop_select\">\r\n");
      out.write("        <!-- 전체선택 : 버튼 -->\r\n");
      out.write("        <button class=\"shop_select_all_bt\"></button>\r\n");
      out.write("        <!-- 전체선택 : 텍스트 -->\r\n");
      out.write("        <h2 id=\"shop_select_all\">전체선택</h2>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 상품디테일 (innerHTML) -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  		<!--  더미데이터1 -->\r\n");
      out.write("         <!-- 상품 디테일 전체 영역 -->\r\n");
      out.write("         <div class=\"shop_product_detail\">\r\n");
      out.write("         \r\n");
      out.write("         <!--  장바구니에 추가한 컨텐츠를 제거하는 x버튼 -->\r\n");
      out.write("         <a href=\"/\" class=\"shopping_bag_close\">\r\n");
      out.write("         </a>\r\n");
      out.write("\r\n");
      out.write("          <!-- 상품이미지 컨텐츠 영역 -->\r\n");
      out.write("          <div class=\"shopping_bag_product_img\">\r\n");
      out.write("            <!-- 상품 선택 버튼 -->\r\n");
      out.write("            <button class=\"shop_select_all_bt\"></button>\r\n");
      out.write("          <!-- 상품이미지  -->\r\n");
      out.write("          <img src=\"/img/product1.jpg\" alt=\"\">\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <!-- 상품 디테일 텍스트영역 -->\r\n");
      out.write("          <div class=\"shopping_bag_product_text\">\r\n");
      out.write("            <!-- 제품명 -->\r\n");
      out.write("            <h1 class=\"shopping_bag_product_name\">UV 프로텍터 액티브 선 밤 SPF 50+ / PA++++</h1>\r\n");
      out.write("            <!-- 수량선택 -->\r\n");
      out.write("  \r\n");
      out.write("            <div class=\"shopping_bag_product_count\">\r\n");
      out.write("              <div class=\"shopping_bag_product_bt\">\r\n");
      out.write("                <button class=\"shopping_bag_product_buy_now\">바로구매하기</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 하단 제품가격을 계산해주는 flex 영역 -->\r\n");
      out.write("    <div class=\"shopping_bag_product_price\">\r\n");
      out.write("      <div class=\"shopping_bag_product_price_wrap\">\r\n");
      out.write("        <div class=\"shopping_bag_product_price_contents\">\r\n");
      out.write("          <h1 class=\"shopping_bag_product_price_text\">총 주문 금액 : 7,000원</h1>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 우측 총주문 버튼 -->\r\n");
      out.write("        <button class=\"shopping_bag_product_order_bt\">총 주문하기</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/modules/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
