/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-12 03:40:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Ezen_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/ezen-fullstack/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project_portfolio_jsp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1688716149719L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <title>PortFolio</title>\r\n");
      out.write("  <!-- meta -->\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- css -->\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/modules/css.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <!--  클릭시 상단으로 이동하는 버튼 -->\r\n");
      out.write("  <a href=\"#wrap01\" class=\"goTop\"></a>\r\n");
      out.write("  \r\n");
      out.write("  <!--  우측 네비게이션 바 -->\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/modules/aside.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <!-- 섹션1 -->\r\n");
      out.write("  <section id=\"wrap01\">\r\n");
      out.write("  <!--  메뉴 리스트 -->\r\n");
      out.write("  	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/modules/menuList.jsp", out, false);
      out.write("\r\n");
      out.write("    <div class=\"circle\"></div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"contents_box\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- 헤더 -->\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/modules/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- 중앙콘텐츠 -->\r\n");
      out.write("      <div class=\"sec_contents_box scb01\">\r\n");
      out.write("        <div class=\"sec_text sct01\">\r\n");
      out.write("          <img src=\"img/circle.png\" alt=\"\">\r\n");
      out.write("          <h1 id=\"song\">Song Woo Sung</h1>\r\n");
      out.write("          <h5>PortFolio</h5>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- 하단 컨텐츠 -->\r\n");
      out.write("      <div class=\"sec_bottom_contents\">\r\n");
      out.write("        <a href=\"#wrap02\"><img src=\"img/icon30.png\" alt=\"\"></a>\r\n");
      out.write("        <h5>Moving Down</h5>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <!-- 섹션 2 -->\r\n");
      out.write("  <section id=\"wrap02\">\r\n");
      out.write("    <!-- 상단 꾸미기용 컨텐츠 -->\r\n");
      out.write("    <h5 class=\"full_stack\">Full Stack DEVELOPER</h5>\r\n");
      out.write("\r\n");
      out.write("    <!-- 중앙콘텐츠 -->\r\n");
      out.write("    <div class=\"sec_contents_box scb02\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"sec_art_contents sac02\">\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"sec_text sct02\">\r\n");
      out.write("        <h1>ABOUT ME</h1>\r\n");
      out.write("        <h5>I AM SONG WOO SUNG!</h5>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"sec_text2\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li id=\"st2_ft\">\r\n");
      out.write("            <h1>ABOUT ME</h1>\r\n");
      out.write("            <div class=\"st2_line\"></div>\r\n");
      out.write("            <p>NAME : 송우성</p>\r\n");
      out.write("            <p>ADRESS : 중랑구 중화1동</p>\r\n");
      out.write("            <p>NUMBER : 010-7728-8364</p>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li>\r\n");
      out.write("            <h1>FRONT END</h1>\r\n");
      out.write("            <div class=\"st2_line\"></div>\r\n");
      out.write("            <p>WHAT CAN I DO?</p>\r\n");
      out.write("            <div class=\"img_box ib01\">\r\n");
      out.write("              <img src=\"img/photoshop.png\" alt=\"\">\r\n");
      out.write("              <img src=\"img/html.png\" alt=\"\">\r\n");
      out.write("              <img src=\"img/css.png\" alt=\"\">\r\n");
      out.write("              <img src=\"img/atom.png\" alt=\"\">\r\n");
      out.write("              <img src=\"img/vscode.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li>\r\n");
      out.write("            <h1>BACK END</h1>\r\n");
      out.write("            <div class=\"st2_line\"></div>\r\n");
      out.write("            <div class=\"img_box ib02\">\r\n");
      out.write("              <img src=\"img/eclipse.png\" alt=\"\">\r\n");
      out.write("              <img src=\"img/sql.png\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li>\r\n");
      out.write("            <h1>LICENSE</h1>\r\n");
      out.write("            <div class=\"st2_line\"></div>\r\n");
      out.write("            <p>GTQ 1급</p>\r\n");
      out.write("            <p>정보처리기사(예정)</p>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 하단 컨텐츠2 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 하단 컨텐츠 -->\r\n");
      out.write("    <div class=\"sec_bottom_contents\">\r\n");
      out.write("      <a href=\"#wrap03\"><img src=\"img/icon30.png\" alt=\"\"></a>\r\n");
      out.write("      <h5>Moving Down</h5>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- 3번 -->\r\n");
      out.write("  <section id=\"wrap03\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"sec_contents_box scb03\">\r\n");
      out.write("      <div class=\"sec_art_contents sac03\">\r\n");
      out.write("        <div class=\"art_text\">\r\n");
      out.write("          <h1>01</h1>\r\n");
      out.write("          <h1>FRONTEND</h1>\r\n");
      out.write("          <p id=\"used_program\">사용된 프로그램</p>\r\n");
      out.write("          <div class=\"img_box1\">\r\n");
      out.write("            <img src=\"img/eclipse.png\" alt=\"\">\r\n");
      out.write("            <img src=\"img/vscode.png\" alt=\"\">\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <p id=\"used_skills\">사용된 기술\r\n");
      out.write("          <p>\r\n");
      out.write("          <div class=\"img_box2\">\r\n");
      out.write("            <img src=\"/img/html.png\" alt=\"\">\r\n");
      out.write("            <img src=\"/img/css.png\" alt=\"\">\r\n");
      out.write("            <img src=\"/img/css.png\" alt=\"\">\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"sec3_right_contents src1\">\r\n");
      out.write("        <div class=\"sec3_contents s3c1\">\r\n");
      out.write("          <img src=\"/img/chat1.png\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sec3_contents s3c2\">\r\n");
      out.write("          <img src=\"/img/code1.png\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"sec3_right_contents src2\">\r\n");
      out.write("        <div class=\"sec3_contents s3c3\">\r\n");
      out.write("          <h1>임시로 넣어본 사진입니다</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sec3_contents s3c4\">\r\n");
      out.write("          <h1>임시로 넣어본 사진입니다</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"sec_content_box\">\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 하단 컨텐츠2 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 하단 컨텐츠 -->\r\n");
      out.write("    <div class=\"sec_bottom_contents sbc03\">\r\n");
      out.write("      <a href=\"#wrap04\"><img src=\"img/icon30.png\" alt=\"\"></a>\r\n");
      out.write("      <h5>Moving Down</h5>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- 4번 -->\r\n");
      out.write("  <section id=\"wrap04\">\r\n");
      out.write("    <div class=\"sec4_position\">\r\n");
      out.write("      <div class=\"sec4_zone\">\r\n");
      out.write("        <div class=\"sec4_text_box\">\r\n");
      out.write("          <h2>02</h2>\r\n");
      out.write("          <h2>BACKEND</h2>\r\n");
      out.write("          <P>Lorem ipsum dolor sit, amet consectetur adipisicing elit. <br>\r\n");
      out.write("            Aut minima voluptatum sed, itaque maxime veritatis<br> reprehenderit quasi laboriosam minus a consequuntur\r\n");
      out.write("            <br>\r\n");
      out.write("            repellendus reiciendis quis illo eos nisi<br> obcaecati molestiae similique.\r\n");
      out.write("          </P>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sec4_contents_box1\">\r\n");
      out.write("          <div class=\"sec4_contents sc01\">\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"sec4_contents sc02\">\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sec4_contents_box2\">\r\n");
      out.write("          <div class=\"sec4_contents sc03\">\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"sec4_contents sc04\">\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 하단 컨텐츠 -->\r\n");
      out.write("    <div class=\"sec_bottom_contents\">\r\n");
      out.write("      <a href=\"#wrap05\"><img src=\"img/icon30.png\" alt=\"\"></a>\r\n");
      out.write("      <h5>Moving Down</h5>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- 05 -->\r\n");
      out.write("  <section id=\"wrap05\">\r\n");
      out.write("    <div class=\"sec5_contents_box\">\r\n");
      out.write("     <ul class=\"sec5_contents\">\r\n");
      out.write("      <li></li>\r\n");
      out.write("      <li></li>\r\n");
      out.write("      <li></li>\r\n");
      out.write("      <li></li>\r\n");
      out.write("     </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <h1>Thank You For Watching</h1>\r\n");
      out.write("  \r\n");
      out.write("  </section>\r\n");
      out.write("  06\r\n");
      out.write("  <section id=\"wrap06\">\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- 07 -->\r\n");
      out.write("  <section id=\"wrap07\">\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- 08 -->\r\n");
      out.write("  <section id=\"wrap08\">\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- 09 -->\r\n");
      out.write("  <section id=\"wrap09\">\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- 10 -->\r\n");
      out.write("  <section id=\"wrap10\">\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- 11 -->\r\n");
      out.write("  <section id=\"wrap11\">\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- 12 -->\r\n");
      out.write("  <section id=\"wrap12\">\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- 13 -->\r\n");
      out.write("  <section id=\"wrap13\">\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/modules/script.jsp", out, false);
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\" src=\"/js/script.js\">\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
